files:
  - source: en-3dtouch.properties
    translation: >-
      /%two_letters_code%/%language%/%three_letters_code%/%locale%/%locale_with_underscore%/%android_code%/%osx_code%/%osx_locale%/3dtouch.properties
    languages_mapping:
      two_letters_code:
        pt-PT: po
      language:
        uk: ads
      three_letters_code:
        uk: asdf
      locale:
        uk: asdff
      locale_with_underscore:
        uk: qewr143
      android_code:
        uk: nvbcbvn
      osx_code:
        uk: vbcnxc
      osx_locale:
        uk: eradf
export_languages:
  - uk
